name: Change pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.0.0
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm ci
    - name: Execute build
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build-artifact
        path: ./dist
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.0.0
      - name: Download artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: build-artifact
          path: ./dist
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
      - name: Install dependencies
        run: npm ci
      - name: Testing annotations
        run: echo "::error file=src/learning-library-workflow.ts,line=3,col=3::Testing annotations!"
      - name: Execute unit tests
        run: npm run test
      - name: Execute tests with coverage
        run: npm run coverage
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.0.0
      - name: Download artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: build-artifact
          path: ./dist
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
      - name: Install dependencies
        run: npm ci
      - name: Execute linting
        run: npm run lint
