name: Change pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.0.0
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm ci
    - name: Execute build
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build-artifact
        path: .
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: build-artifact
      - name: Execute tests with coverage
        run: npm run coverage
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1.0.0
        with:
          name: build-artifact
      - name: Execute linting
        run: npm run lint
